### ISSUE TITLE
Is this repo hosting completed solution?

### ISSUE THREAD

**Issue by sillysachin** [happilymarrieddad/hyperledger-fabric-kubernetes#1]
I purchased the course on udemy. I do not see the kubernetes  part yet in the course running the completed vue ui , backend goland and network hyperledger !!!!!

**Comment by happilymarrieddad** [comment]
@sillysachin Hello, no it is not completed yet. I'm trying to do a video or two every day. I have the whole code base completed and I have a production Kubernetes Hyperledger network with dynamically building organizations. Thanks so much for purchasing the course and stay tuned for the rest of the series which I will be completed very shortly. Thanks!
